# Generated by Django 4.2 on 2026-04-06 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="total_discount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
